pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "ClassApp"
include(":app")
include(":class-app-submissions:class-app-abeloy4:app")
include(":class-app-submissions:class-app-Abhiabhishek5124:app")
include(":class-app-submissions:class-app-alexjoness1999:app")
include(":class-app-submissions:class-app-bata1110:app")
include(":class-app-submissions:class-app-blaiseghering:app")
include(":class-app-submissions:class-app-BrokenWhiteRice:app")
include(":class-app-submissions:class-app-cardslinger:app")
include(":class-app-submissions:class-app-ColaTonic:app")
include(":class-app-submissions:class-app-DaRealSun:app")
include(":class-app-submissions:class-app-DevynFerman:app")
include(":class-app-submissions:class-app-drerid:app")
include(":class-app-submissions:class-app-EmmaNHop:app")
include(":class-app-submissions:class-app-ghxc2:app")
include(":class-app-submissions:class-app-HatInTime1:app")
include(":class-app-submissions:class-app-Hunt-E:app")
include(":class-app-submissions:class-app-Jackiee2002:app")
include(":class-app-submissions:class-app-justinweyer:app")
include(":class-app-submissions:class-app-kaleabtesfaye01:app")
include(":class-app-submissions:class-app-KennyBarth:app")
include(":class-app-submissions:class-app-khanhnguyen522:app")
include(":class-app-submissions:class-app-lineh1:app")
include(":class-app-submissions:class-app-manogya1:app")
include(":class-app-submissions:class-app-MattMadix:app")
include(":class-app-submissions:class-app-NLama77:app")
include(":class-app-submissions:class-app-NorthNorth1986:app")
include(":class-app-submissions:class-app-osifalujoi1:app")
include(":class-app-submissions:class-app-PowersC10:app")
include(":class-app-submissions:class-app-pragyanbt:app")
include(":class-app-submissions:class-app-saaumyaa:app")
include(":class-app-submissions:class-app-Salem3j:app")
include(":class-app-submissions:class-app-smaligi2:app")
include(":class-app-submissions:class-app-springerc4:app")
include(":class-app-submissions:class-app-Starlight86:app")
include(":class-app-submissions:class-app-Suman9959:app")
include(":class-app-submissions:class-app-trietluong1602:app")
include(":class-app-submissions:class-app-TurtleTerritory:app")
include(":class-app-submissions:class-app-wasiuogunlana:app")
include(":class-app-submissions:class-app-WhaleWithFeet:app")
include(":class-app-submissions:class-app-xander-cs:app")